### ISSUE TITLE
Compile Error:  module :triq_dom is not loaded and could not be found

### ISSUE THREAD

**Issue by lpil** [parroty/excheck#10]
Hello! All I've done is add this library as a dep to my mix.exs and added `use ExCheck`, and I'm getting compile errors.

Is there more than needs to be done? If so, can we add this to the README?

```
louis ~/projects/osc [master *+] $ MIX_ENV=test mix deps.compile excheck
==> excheck
Compiled lib/excheck/generator.ex
Compiled lib/excheck/predicate.ex
Compiled lib/excheck/error.ex
Compiled lib/excheck.ex
Compiled lib/excheck/statement.ex

== Compilation error on file lib/excheck/sample.ex ==
** (CompileError) lib/excheck/sample.ex:5: module :triq_dom is not loaded and could not be found
    expanding macro: ExCheck.Generator.__using__/1
    lib/excheck/sample.ex:5: ExCheck.Sample (module)
    (elixir) expanding macro: Kernel.use/1
    lib/excheck/sample.ex:5: ExCheck.Sample (module)
    expanding macro: ExCheck.__using__/1
    lib/excheck/sample.ex:5: ExCheck.Sample (module)
    (elixir) expanding macro: Kernel.use/1
    lib/excheck/sample.ex:5: ExCheck.Sample (module)

could not compile dependency excheck, mix compile failed. You can recompile this dependency with `mix deps.compile excheck` or update it with `mix deps.update excheck`
```

**Comment by parroty** [comment]
Hi. Could you try adding `:triq` in the `deps` section of mix.exs if it's not defined? I'll update the README if this is the case.
```elixir
  defp deps do
    [
      {:excheck, "~> 0.2"},
      {:triq, github: "krestenkrab/triq"}
    ]
  end
```

**Comment by lpil** [comment]
Thanks for the quick reply. It seems to work with that modification.

Would it be possible to get triq on hex.pm so mix can handle the dependency?

**Comment by parroty** [comment]
Thanks for the update. I don't have permission for the triq library. One option might be requesting at https://github.com/krestenkrab/triq :smile:

**Comment by parroty** [comment]
Thank you for requesting it. Please let me close this item at the moment, and let me track the above issue item in triq (as fix is possible in either hex or triq).
